// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import SidebarController from "./sidebar_controller"
import DropdownController from "./dropdown_controller"
import ToastController from "./toast_controller"

application.register("hello", HelloController)
application.register("sidebar", SidebarController)
application.register("dropdown", DropdownController)
application.register("toast", ToastController)
